# Generated by Django 4.0.2 on 2022-02-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Student',
        ),
    ]
