# Generated by Django 4.0.2 on 2022-04-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_year_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(default=2023, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='issue_year',
            field=models.CharField(default='2023', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
